#!/usr/bin/env bash
#Install and Configure HAproxy on lb-01 to send traffic to web-01 and web-02

apt-get -y update
apt-get install --no-install-recommends -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get install -y haproxy=2.8.\*

cat <<EOL | sudo tee /etc/haproxy/haproxy.cfg
global
  maxconn 60000
  log 127.0.0.1 local0
  log 127.0.0.1 local1 notice
  user  haproxy
  group haproxy
  chroot /var/empty
defaults
  log global
  mode http
  option httplog
  option dontlognull
  timeout connect 5000
  timeout client 50000
  timeout server 50000
frontend myfrontend
  mode http
  bind :80
  default_backend web_servers
backend web_servers
  mode http
  balance roundrobin
  server 400500-web-01  100.25.197.148:80 check
  server 400500-web-02  54.158.210.206:80 check
EOL

service haproxy restart
